aaa

diff --git a/.github/workflows/auto_merge.yml b/.github/workflows/auto_merge.yml
--- a/.github/workflows/auto_merge.yml
+++ b/.github/workflows/auto_merge.yml
@@ -1,56 +1,90 @@
 name: Auto Merge PR
 
-# on:
-#   pull_request:
-#     types:
-#       - closed
-
 on:
   pull_request:
     types:
-      - opened
+      - closed
+  push:
+    branches:
+      - main
 
 jobs:
   if_merged:
     runs-on: ubuntu-latest
-
+    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
-      - name: Get Branches with Tag
-        id: branches_with_tag
-        run: |
-          BRANCHES=$(curl -s -H "Authorization: token ${{ github.token }}" "https://api.github.com/repos/${{ github.repository }}/git/matching-refs/tags/asdf" | jq -r '.[].ref' | awk -F/ '{print $3}')
-          echo "::set-output name=branches_with_tag::$BRANCHES"
-
-          # TAG_NAME="asdf"
-          # BRANCHES=$(git for-each-ref --format='%(refname:short)' refs/heads/ --contains "refs/tags/$TAG_NAME")
-          # echo "::set-output name=branches_with_tag::$BRANCHES"
-
-      - name: Display Branches with Tag
-        run: |
-          echo "Branches with Tag: ${{ steps.branches_with_tag.outputs.branches_with_tag }}"
-
-      - name: Check if PR is closed
-        id: doing
+      - name: Merge Main to Branches
         run: |
           echo "Run Auto-Merge script."
 
-          PR_NUMBER=$(jq -r '.pull_request.number' < "$GITHUB_EVENT_PATH")
-          PR_STATE=$(jq -r '.pull_request.state' < "$GITHUB_EVENT_PATH")
-          BRANCH_NAME=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
-            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" | jq -r '.head.ref')
+          BRANCHES=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
+          "https://api.github.com/repos/${{ github.repository }}/branches" | jq -r '.[].name')
 
-            # declare -a DESIRED_BRANCHES=("branch1" "branch2" "branch3")
-            # for DESIRED_BRANCH in "${DESIRED_BRANCHES[@]}"; do
-            #   if [ "$PR_STATE" = "closed" ]; then
-            #     echo "Merging PR $PR_NUMBER to $DESIRED_BRANCH branch"
-            #     git config user.name github-actions
-            #     git config user.email github-actions@github.com
-            #     git checkout "$DESIRED_BRANCH"
-            #     git merge "$BRANCH_NAME" --no-ff --no-commit
-            #     git commit -m "Auto-merge PR #$PR_NUMBER to $DESIRED_BRANCH branch"
-            #     git push origin "$DESIRED_BRANCH"
-            #   fi
-            # done
+          SUCCESS="[]"
+          FAILURE="[]"
+          CONFLICT="[]"
+
+          for BRANCH in $BRANCHES; do
+            catch() {
+              echo "$BRANCH에서 하자 발생."
+              # curl -H 'Content-type: application/json' \
+              #   --data '{"text":"*'"$BRANCH"'*에서 에러가 발생했습니다."}' \
+              #   -H "Authorization: Bearer ${{ github.token}}" \
+              #   -X POST ${{ secrets.SLACK_FE_AUTO_BOT_WEBHOOK_URL }}
+              return 0
+            }
+
+            trap catch ERR
+
+            if echo "$BRANCH" | grep -qE '[0-9]{4}-[0-9]{2}-[0-9]{2}'; then
+              BRANCH_DATE=$(echo "$BRANCH" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}')
+              CURRENT_DATE=$(date +'%Y-%m-%d')
+
+              if [[ "$BRANCH_DATE" > "$CURRENT_DATE" ]]; then
+                echo "Merge main to $BRANCH branch"
+
+                MERGE_RESPONSE=$(curl -i -L \
+                  -X POST -H "Accept: application/vnd.github+json" \
+                  -H "Authorization: Bearer ${{github.token}}" \
+                  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/merges \
+                  -d '{"base":"'"$BRANCH"'", "head": "main", "commit_message": "Merge"}')
+
+                echo $MERGE_RESPONSE
+                  
+                STATUS_CODE=$(echo "$MERGE_RESPONSE" | grep -o -P '(?<=HTTP/2 )[0-9]+')
+                  
+                if [ $STATUS_CODE -ge 200 ] && [ $STATUS_CODE -lt 300 ]; then
+                  SUCCESS="${SUCCESS::-1}, '${BRANCH}']"
+                  # curl -H 'Content-type: application/json' \
+                  #   --data '{"text":"[SUCCESS] The merge from main to *'"$BRANCH"'* was successful.", "attachments": [{"color": "good", "text": "[SUCCESS]", "footer": "Slack Notification"}]}' \
+                  #   -H "Authorization: Bearer ${{ github.token}}" \
+                  #   -X POST ${{ secrets.SLACK_FE_AUTO_BOT_WEBHOOK_URL }}
+                elif [ $STATUS_CODE == 409 ]; then
+                  CONFLICT="${CONFLICT::-1}, ${BRANCH}]"
+                  # curl -H 'Content-type: application/json' \
+                  #   --data '{"text":"[CONFLICT : '"$STATUS_CODE"'] The merge from main to *'"$BRANCH"'* conflicted.", "attachments": [{"color": "danger", "text": "CONFLICT", "footer": "Slack Notification"}]}' \
+                  #   -H "Authorization: Bearer ${{ github.token}}" \
+                  #   -X POST ${{ secrets.SLACK_FE_AUTO_BOT_WEBHOOK_URL }}
+                else
+                  FAILURE="${FAILURE::-1}, ${BRANCH}]"
+                  # curl -H 'Content-type: application/json' \
+                  #   --data '{"text":"[FAILED : '"$STATUS_CODE"'] The merge from main to *'"$BRANCH"'* failed.", "attachments": [{"color": "danger", "text": "FAILED", "footer": "Slack Notification"}]}' \
+                  #   -H "Authorization: Bearer ${{ github.token}}" \
+                  #   -X POST ${{ secrets.SLACK_FE_AUTO_BOT_WEBHOOK_URL }}
+                fi
+              fi
+            fi
+          done
+
+          echo $SUCCESS
+          echo $CONFLICT
+          echo $FAILURE
+
+          A=$(node -e "const arrStr = $SUCCESS.slice(1);  console.log(arrStr.join(', '));")
+
+          echo A
+
+          # echo $SUCCESS | jq -r '. | join(",")'
