auto merge cron

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -1,81 +1,68 @@
-name: cron_test
+name: Auto Back Merge Cron
 
 on:
   schedule:
-    - cron: "*/5 * * * *"
+    - cron: "30 6,13 * * 1-5"
 
 jobs:
-  cron:
+  cron_schedule:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+        uses: actions/checkout@v2
 
-      - name: Use Node.js 20.x
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20.x
-
-      - name: Get Tags named dev or staging
-        id: get-tags
+      - name: Merge Main to Branches
         run: |
-          TAGS=$(curl -L \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{ github.token }}" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              "https://api.github.com/repos/${{ github.repository }}/git/refs/tags" | jq -r '.[] | select(.ref | contains("staging") or contains("dev")) | {name: .ref | split("/") | last, sha: .object.sha}')
+          echo "Run Auto-Merge script."
 
-          echo $TAGS
-          echo "tags=$TAGS" >> $GITHUB_OUTPUT
+          BRANCHES=("main" "staging" "dev")
 
-      - name: Set staging/dev branches
-        run: |
-          STAGING_BRANCH=""
-          DEV_BRANCH=""
+          for ((i=0; i<${#BRANCHES[@]}-1; i++)); do
+            catch() {
+                echo "$BRANCH에서 하자 발생."
+                curl -H 'Content-type: application/json' \
+                --data '{"text":"Git actions - Auto Merge 중 에러가 발생했습니다."}' \
+                -H "Authorization: Bearer ${{ github.token}}" \
+                -X POST ${{ secrets.SLACK_FE_AUTO_BOT_WEBHOOK_URL }}
+                return 0
+            }
 
-          echo $steps.get-tags.outputs.tags
+            trap catch ERR
 
-          for TAG in "${{ steps.get-tags.outputs.tags }}"; do
-            echo $TAG
-            echo $steps.get-tags.outputs.tags
-            NAME=$(echo "$TAG" | jq -r '.name')
-            SHA=$(echo "$TAG" | jq -r '.sha')
+            SOURCE_BRANCH=${BRANCHES[i]}
+            TARGET_BRANCH=${BRANCHES[i+1]}
 
-            if [ $NAME == "staging" ]; then
-              STAGING_BRANCH=$(echo "$(git branch --contains $SHA)" | sed -e 's/ //g; s/\*//g')
-            elif [ $NAME == 'dev' ]; then
-              BRANCHES_STR=$(echo "$(git branch --contains $SHA)" | sed -e 's/ //g; s/\*//g')
-              # IFS='\n' read -r -A BRANCHES <<< $BRANCHES_STR
+            echo "Merge $SOURCE_BRANCH to $TARGET_BRANCH branch"
 
-              # for BRANCH in "${BRANCHES[@]}"; do
-              #   echo $BRANCH
-              # done;
+            MERGE_RESPONSE=$(curl -i -L \
+              -X POST -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{github.token}}" \
+              -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/merges \
+              -d '{"base":"'"$TARGET_BRANCH"'", "head": "'"$SOURCE_BRANCH"'", "commit_message": "Merge"}')
 
-              # DEV_BRANCH=$(echo "$(git branch --contains $SHA)" | sed -e 's/ //g; s/\*//g')
+            echo $MERGE_RESPONSE
+
+            STATUS_CODE=$(echo "$MERGE_RESPONSE" | grep -o -P '(?<=HTTP/2 )[0-9]+')
+
+            if [ $STATUS_CODE -ge 200 ] && [ $STATUS_CODE -lt 300 ]; then
+              echo "Merge successful: $SOURCE_BRANCH to $TARGET_BRANCH"
+              curl -H 'Content-type: application/json' \
+                --data '{"text":"🟢 [Merge Success] *'"$SOURCE_BRANCH to $TARGET_BRANCH"'*"}' \
+                -H "Authorization: Bearer ${{ github.token}}" \
+                -X POST ${{ secrets.SLACK_FE_AUTO_BOT_WEBHOOK_URL }}
+
+            elif [ $STATUS_CODE == 409 ]; then
+              echo "Conflict detected: $SOURCE_BRANCH to $TARGET_BRANCH"
+              curl -H 'Content-type: application/json' \
+                --data '{"text":"🔴 [Merge Conflict] *'"$SOURCE_BRANCH to $TARGET_BRANCH"'*"}' \
+                -H "Authorization: Bearer ${{ github.token}}" \
+                -X POST ${{ secrets.SLACK_FE_AUTO_BOT_WEBHOOK_URL }}
+
             else
-              echo "Staging / Dev 환경으로 추정되는 브랜치가 없습니다."
-              exit 1;
-            fi;
-          done;
-
-          echo $STAGING_BRANCH
-          echo $DEV_BRANCH
-
-          if [ -z $STAGING_BRANCH or -z $DEV_BRANCH ]; then
-              echo "Staging / Dev 환경으로 추정되는 브랜치가 없습니다."
-              exit 1;
-          fi;
-
-          # git checkout $DEV_BRANCH
-          # git
-
-      # - name: notify to slack
-      #   run: |
-      #     curl \
-      #       -X POST \
-      #       --data-urlencode \
-      #       "payload={\"channel\": \"#test-for-slack-notification\", \"username\": \"webhookbot\", \"text\": \"이 항목은 #개의 my-channel-here에 포스트되며 webhookbot이라는 봇에서 제공됩니다.\", \"icon_emoji\": \":ghost:\"}" \
-      #       https://hooks.slack.com/services/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
+              echo "Merge failed: $SOURCE_BRANCH to $TARGET_BRANCH"
+              curl -H 'Content-type: application/json' \
+                --data '{"text":"🔴 [Merge Failed] *'"$SOURCE_BRANCH to $TARGET_BRANCH"'*"}' \
+                -H "Authorization: Bearer ${{ github.token}}" \
+                -X POST ${{ secrets.SLACK_FE_AUTO_BOT_WEBHOOK_URL }}
+            fi
+          done
